### ISSUE TITLE
Support normalization using multiple reference proteins

### ISSUE THREAD

**Issue by olschu** [biodavidjm/artMS#174]
Hi David,

It would be great if we could use multiple reference genes at once (I think MSstats does accept a vector of genes for this, see "nameStandards" in MSstats manual). 

When I tried to give a vector in the config file for artMS I got the following error: 

Error in dataProcess(raw = dmss, normalization = config$msstats$normalization_method,  :
  global standard peptides or proteins,  c("YFL039C" , is not in dataset. Please check whether 'nameStandards' input is correct or not

Thank you!
Olga

**Comment by biodavidjm** [comment]
Hi Olga,

it turns out that artMS supports that feature as well. You just need to provide the list of protein ids comma separated. For example, if you want to use these two proteins `Q86U42, O75822` as reference for normalization, in the yaml file, `msstats` section, you would write:

```
  normalization_method: globalStandards
  normalization_reference: Q86U42, O75822
```

Please, give it a try and let us know if there is any problem.

And thanks for the feedback. We will update the artMS documentation in the next release to make it more clear.

**Comment by olschu** [comment]
Hi David,

Thanks for looking into this. Great to hear that it actually works already!

Many thanks and best wishes,
Olga

**Comment by olschu** [comment]
Hi David,

I just wanted to report that I tried this with multiple genes and it worked well.

Thanks,
Olga

**Comment by biodavidjm** [comment]
Thanks!
